#!/bin/sh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for x in mount umount sv pacman updatedb su ; do
	alias $x="sudo $x"
done

# Verbosity and settings that you pretty much just always are going to want.
alias \
	vim="nvim" \
	vimdiff="nvim -d" \
	batt="acpi" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"\
	vtop="vtop -t nord"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	l="ls -l" \
	ll"ls -la" \
	ls="exa --color=always" \
	lh="ls -alt=changed | head -n 15" \
	la="ls -alFh" \
	ld="ls -ld .*" \
	lr="ls -R" \
	dud='du -d 1 -h' \
	duf='du -sh *' \
	diff="diff --color=auto" \
	cat="bat"

# Git shortcuts
alias \
	gi='git init' \
	gl='git log' \
	ga='git add' \
	gaa='git add .' \
	gs='git status' \
	gc='git commit -m' \
	gpom='git push origin master' \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	sdn="sudo shutdown -h now" \
	sdr="sudo shutdown -r now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	Z="zathura"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	:q="exit" \
	j="z" \
	c="clear" \
	clear-password-cache="gpgconf --reload gpg-agent" \
	pirate-get="pirate-get -C peerflix %s -m" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \

# Tree
alias t1='tree -L 1'
alias t1a='tree -La 1'
alias t2='tree -L 2'
alias t2a='tree -La 2'
alias t3='tree -L 3'
alias t3a='tree -La 3'
alias t4='tree -L 4'
alias t4a='tree -La 4'
alias tree='tree -CF'


# homestead aliases
alias \
	hp='homestead provision' \
	hu='homestead up' \
	hr='homestead reload' \
	hs='homestead suspend' \
	hh='homestead halt' \
	hssh='homestead ssh'

# laravel aliases
alias \
	a='php artisan' \
	art='php artisan' \
	amc="php artisan make" \
	amc="php artisan make:controller" \
	ame="php artisan make:event" \
	amj="php artisan make:job" \
	amm="php artisan make:migration" \
	amr="php artisan make:request" \
	ams="php artisan make:seeder" \
	amt="php artisan make:test" \
	aia="php artisan infyom:api" \
	aias="php artisan infyom:api_scaffold" \
	aim="php artisan infyom:model" \
	aiM="php artisan infyom:migration" \
	aip="php artisan infyom:publish" \
	air="php artisan infyom:repository" \
	aiR="php artisan infyom:rollback" \
	ais="php artisan infyom:scaffold" \
	apic="php artisan infyom.api:controller" \
	apir="php artisan infyom.api:request" \
	apit="php artisan infyom.api:tests" \
	isc="php artisan infyom.scaffold:controller" \
	isr="php artisan infyom.scaffold:request" \
	isv="php artisan infyom.scaffold:views" \
	test="./vendor/bin/phpunit"
